### ISSUE TITLE
Fehlermeldung Bootstraping

### ISSUE THREAD

**Issue by gma-lks** [statistikZH/decarb_monitoring#25]
Fehlermeldung beim Start:
# Bootstrapping renv 0.15.4 --------------------------------------------------
* Downloading renv 0.15.4 ... FAILED
Error in bootstrap(version, libpath) : failed to download renv 0.15.4

**Comment by philbosch** [comment]
sollte damit gelöst sein: 2f036e58f8436757f1e4c0ca8af88801a67669d0
renv() ist optional für das Projekt, haben es deshalb entfernt. Bei Interesse an renv hier etwas Hintergrund: https://rstudio.github.io/renv/articles/renv.html

**Comment by gma-lks** [comment]
Perfekt! Danke auch für die Hintergrundinfo
