### ISSUE TITLE
Error in download_data(ds)

### ISSUE THREAD

**Issue by gma-lks** [statistikZH/decarb_monitoring#28]
Beim Bezug der Daten aus STAT-TAB erscheint bei mir seit kurzem folgende Fehlermeldung:
![Screenshot 2024-04-08 094054](https://github.com/statistikZH/decarb_monitoring/assets/83970422/6b80ea6b-a902-4b0b-8bd7-e19e31ca8e7d)
Soweit ich weiss, wurde am Code nichts geändert. Bei mir hat das im Februar noch problemlos funktioniert.
Der Fehler bezieht sich auf folgenden Code-Teil (decarb_monitoring/R/download_helpers.R):
![Screenshot 2024-04-08 094420](https://github.com/statistikZH/decarb_monitoring/assets/83970422/c9100950-8406-4ba0-a8a2-10336f6da7c0)
Hab noch ein wenig versucht, ds$asset_number in Einzelschritten durchzuführen. Beim rvest::html_text(ds$data_id) %>% steh ich aber immer an.
Die anschliessende Zuweisung ds$year_end hat dann wiederum problemlos geklappt.

**Comment by philbosch** [comment]
@gma-lks was passiert, wenn du `ds$data_id` entfernst? 
Also:
`  ds$asset_number <- asset_page %>%
    rvest::html_text() %>%
    stringr::str_extract("https://.*assets/.*/") %>%
    stringr::str_extract("[0-9]+")`

**Comment by gma-lks** [comment]
@philbosch: this is it! Danke dir.
