### ISSUE TITLE
download bzw einlesen gezippter *.csv fails

### ISSUE THREAD

**Issue by gma-lks** [statistikZH/decarb_monitoring#33]
Für den Indikator A1 "Kehrichtverwertungsanlagen (KVA)" stehen aktuelle Zahlen für das Jahr 2023 zur Verfügung.
Bei der Nachführen der Daten erscheint beim Download jedoch folgende Fehlermeldung:

![image](https://github.com/statistikZH/decarb_monitoring/assets/83970422/5eae6eb5-3734-4680-b8ca-25a161fd7d2f)

Das tempfile existiert jedoch und auch eine extension ist vorhanden.
In der function download_data steht der Code an folgender Stelle an

![image](https://github.com/statistikZH/decarb_monitoring/assets/83970422/3458a65b-05a1-47b0-a049-5daa5aada1cf)

Any ideas?

**Comment by philbosch** [comment]
Update: 
Issue gefunden und es ist eigentlich etwas gutes. Wir können nun auch auf dem DAP mit ´curl´ Dateien herunterladen und müssen nicht mehr auf ´wininet´ ausweichen. Damit können wir sowohl auf dem Linux R-Server als auch auf dem DAP die gleiche Methode verwenden und wir sparen uns etwas Code und Komplexität. 

Werde den fix morgen auf einem Branch implementieren und dich @gma-lks als reviewer zuweisen 🚀

**Comment by philbosch** [comment]
@gma-lks 
Habe den fix aus Versehen direkt auf dem Main Branch implementiert. Kannst gerne testen :)

**Comment by gma-lks** [comment]
Guten Morgen @philbosch 
Irgendwie hakt es noch. File wird runtergeladen und als temp.zip gespeichert. Bei der weiteren Verarbeitung steht der Code (zumindest bei mir) noch an...
![image](https://github.com/statistikZH/decarb_monitoring/assets/83970422/3fbac2c8-ecd3-4438-af3e-00be2b75a66d)

Das mit der "file" has no extension-Meldung ist komisch, denn in "download_data.R":
![image](https://github.com/statistikZH/decarb_monitoring/assets/83970422/928f3069-868a-4702-8ff3-84f2d48763e0)

**Comment by philbosch** [comment]
@gma-lks 
Gute Lehre an mich, nie etwas kurz vor oder im Urlaub zu implementieren. 
Habe es gerade mit @ThomasKnecht angeschaut und können den Fehler beide nicht auf dem DAP replizieren. Am einfachsten wohl, wenn wir es schnell per Call anschauen.

**Comment by philbosch** [comment]
fixed with commit https://github.com/statistikZH/decarb_monitoring/commit/644459591f94bde38a95ba4392378ec9d4b075cb
- bump version of rio to 1.1.1 --> https://github.com/statistikZH/decarb_monitoring/commit/644459591f94bde38a95ba4392378ec9d4b075cb
