### ISSUE TITLE
Check function download_data

### ISSUE THREAD

**Issue by gma-lks** [statistikZH/decarb_monitoring#34]
Guten Morgen @philbosch 
Bei der download_data function ist ein wenig der Wurm drin. Beim Indikator M5 ("[Durchschnittliche CO₂-Emissionen der Personenwagen, Kanton Zürich und Schweiz](https://www.zh.ch/de/umwelt-tiere/klima/langfristige-klimastrategie/monitoring/dekarbonisierung-mobilitaet.html)") steht der Download an

![image](https://github.com/statistikZH/decarb_monitoring/assets/83970422/9548eff4-3224-48f9-974d-79fd3e209a98)

URL stimmt, packages  sind auf dem neusten Stand, pull initial auch durchgeführt.
Die Daten habe ich mit einem Workaround (der nicht mehrheitsfähig ist :-)) bezogen und den Indikator nachgeführt. 
Daher eilt das nicht, mag es trotzdem platzieren.

**Comment by philbosch** [comment]
@gma-lks 
Bei mir läuft der download sowohl auf dem Server als auch auf dem DAP. Könnte es mit der grösseren Störung der IT gestern zusammenhängen? Gestern konnte ich mit dem R-Server nicht mal Pakete installieren, da der Zugang zum Internet geblockt war.

**Comment by gma-lks** [comment]
@philbosch
Nein, sieht nicht so aus. Bei mir hakt da etwas generell. Hab die einzelnen Indikatoren kurz durchgecheckt, neben M5 steht der Download auch G4 an. Ist die gleiche Art von Download:

G4 -> Error in download.file(url = ds$read_path, destfile = temp_file, mode = "wb") : 
  cannot open URL 'https://www.stadt-zuerich.ch/content/dam/stzh/gud/Deutsch/UGZ/umwelt-energie/energie-in-zahlen/Heizgradtage/dokumente/HGT%20Z%c3%bcrich_Fluntern_Monats_Jahreswerte_Zeitreihe_seit_1990.xlsx'
  
M5 -> Error in download.file(url = ds$read_path, destfile = temp_file, mode = "wb") : 
  cannot open URL 'https://www.uvek-gis.admin.ch/BFE/ogd/21/data_t4.csv'

Können wir am einfachsten in einem kurzen Call gemeinsam anschauen. Was meinst du? Eilt nicht.
